### PR TITLE
fixes the mechanoid bug

### PR DESCRIPTION
**Pull request by VernaSaurus**
bazinga

### CODE REVIEW

**Comment by VernaSaurus** [comment]
tested and stuff it works perfectly with this one single change

**Comment by Sicae-lp** [comment]
Recreated pull request locally.  Fixes issue.

**Comment by Chatter42** [comment]
forgive me, but where would I put this exactly? I downloaded the release and changed the relevant line and it does not seem to work for me.

**Comment by nikotin98** [comment]
this is what I get after implementing the fix:

Exception in JobDriver tick for pawn Mech_Constructoid61768 driver=JobDriver_Maintenance (toilIndex=1) driver.job=(FluffyBreakdowns_Maintenance (Job_509970) A=Thing_VFE_LargeBattery112822)
System.NullReferenceException: Object reference not set to an instance of an object
  at Fluffy_Breakdowns.JobDriver_Maintenance+<>c__DisplayClass3_0.<MakeNewToils>b__0 () [0x00036] in <a1c7149df60a40afb73fef16e2ea1bb5>:0 
  at Verse.AI.JobDriver.DriverTick () [0x00163] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
(wrapper dynamic-method) Verse.AI.JobUtility:Verse.AI.JobUtility.TryStartErrorRecoverJob_Patch0 (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.JobDriver:DriverTick ()
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch2 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()


and they still dont do the Maintenance

**Comment by Karel-Kroeze** [comment]
thank you!

**Pull request merged**
